/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "admproto.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

void
adm_program_2(rqstp, transp)
	struct svc_req *rqstp;
	register SVCXPRT *transp;
{
	union {
		cfs_attachargs admproc_attach_2_arg;
		cfs_detachargs admproc_detach_2_arg;
	} argument;
	char *result;
	bool_t (*_xdr_argument)(), (*_xdr_result)();
	char *(*local)();

	switch (rqstp->rq_proc) {
	case ADMPROC_NULL:
		_xdr_argument = xdr_void;
		_xdr_result = xdr_void;
		local = (char *(*)()) admproc_null_2;
		break;

	case ADMPROC_ATTACH:
		_xdr_argument = xdr_cfs_attachargs;
		_xdr_result = xdr_cfsstat;
		local = (char *(*)()) admproc_attach_2;
		break;

	case ADMPROC_DETACH:
		_xdr_argument = xdr_cfs_detachargs;
		_xdr_result = xdr_cfsstat;
		local = (char *(*)()) admproc_detach_2;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)(&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}
