/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "admproto.h"

bool_t
xdr_cfsstat (xdrs, objp)
	XDR *xdrs;
	cfsstat *objp;
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_ciphers (xdrs, objp)
	XDR *xdrs;
	ciphers *objp;
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_adm_deskey (xdrs, objp)
	XDR *xdrs;
	cfs_adm_deskey *objp;
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->pl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_adm_3deskey (xdrs, objp)
	XDR *xdrs;
	cfs_adm_3deskey *objp;
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->pl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary1, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary2, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary1, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary2, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_adm_t3deskey (xdrs, objp)
	XDR *xdrs;
	cfs_adm_t3deskey *objp;
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->pl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary1, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary2, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary3, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary1, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary2, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary3, 8,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_adm_blowkey (xdrs, objp)
	XDR *xdrs;
	cfs_adm_blowkey *objp;
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->pl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary, 16,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary, 16,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_adm_mcgkey (xdrs, objp)
	XDR *xdrs;
	cfs_adm_mcgkey *objp;
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->pl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary, 16,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary, 16,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_adm_saferkey (xdrs, objp)
	XDR *xdrs;
	cfs_adm_saferkey *objp;
{
	register int32_t *buf;

	int i;
	 if (!xdr_long (xdrs, &objp->pl))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->primary, 16,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->secondary, 16,
		sizeof (u_char), (xdrproc_t) xdr_u_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_admkey (xdrs, objp)
	XDR *xdrs;
	cfs_admkey *objp;
{
	register int32_t *buf;

	 if (!xdr_ciphers (xdrs, &objp->cipher))
		 return FALSE;
	switch (objp->cipher) {
	case CFS_STD_DES:
		 if (!xdr_cfs_adm_deskey (xdrs, &objp->cfs_admkey_u.deskey))
			 return FALSE;
		break;
	case CFS_THREE_DES:
		 if (!xdr_cfs_adm_3deskey (xdrs, &objp->cfs_admkey_u.des3key))
			 return FALSE;
		break;
	case CFS_BLOWFISH:
		 if (!xdr_cfs_adm_blowkey (xdrs, &objp->cfs_admkey_u.blowkey))
			 return FALSE;
		break;
	case CFS_MACGUFFIN:
		 if (!xdr_cfs_adm_mcgkey (xdrs, &objp->cfs_admkey_u.mcgkey))
			 return FALSE;
		break;
	case CFS_SAFER_SK128:
		 if (!xdr_cfs_adm_saferkey (xdrs, &objp->cfs_admkey_u.saferkey))
			 return FALSE;
		break;
	case CFS_TRUE_THREE_DES:
		 if (!xdr_cfs_adm_t3deskey (xdrs, &objp->cfs_admkey_u.tdes3key))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}

bool_t
xdr_cfs_attachargs (xdrs, objp)
	XDR *xdrs;
	cfs_attachargs *objp;
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_string (xdrs, &objp->dirname, CFS_MAXNAME))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->name, CFS_MAXCOMP))
			 return FALSE;
		 if (!xdr_cfs_admkey (xdrs, &objp->key))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->uid))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->highsec))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->anon))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->expire))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->idle))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->smsize))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->uid);
			IXDR_PUT_LONG(buf, objp->highsec);
			IXDR_PUT_BOOL(buf, objp->anon);
			IXDR_PUT_LONG(buf, objp->expire);
			IXDR_PUT_LONG(buf, objp->idle);
			IXDR_PUT_LONG(buf, objp->smsize);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_string (xdrs, &objp->dirname, CFS_MAXNAME))
			 return FALSE;
		 if (!xdr_string (xdrs, &objp->name, CFS_MAXCOMP))
			 return FALSE;
		 if (!xdr_cfs_admkey (xdrs, &objp->key))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 6 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->uid))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->highsec))
				 return FALSE;
			 if (!xdr_bool (xdrs, &objp->anon))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->expire))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->idle))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->smsize))
				 return FALSE;
		} else {
			objp->uid = IXDR_GET_LONG(buf);
			objp->highsec = IXDR_GET_LONG(buf);
			objp->anon = IXDR_GET_BOOL(buf);
			objp->expire = IXDR_GET_LONG(buf);
			objp->idle = IXDR_GET_LONG(buf);
			objp->smsize = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_string (xdrs, &objp->dirname, CFS_MAXNAME))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->name, CFS_MAXCOMP))
		 return FALSE;
	 if (!xdr_cfs_admkey (xdrs, &objp->key))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->uid))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->highsec))
		 return FALSE;
	 if (!xdr_bool (xdrs, &objp->anon))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->expire))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->idle))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->smsize))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cfs_detachargs (xdrs, objp)
	XDR *xdrs;
	cfs_detachargs *objp;
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, CFS_MAXCOMP))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->uid))
		 return FALSE;
	return TRUE;
}
