/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "admproto.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

void *
admproc_null_2(argp, clnt)
	void *argp;
	CLIENT *clnt;
{
	static char clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADMPROC_NULL,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_void, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return ((void *)&clnt_res);
}

cfsstat *
admproc_attach_2(argp, clnt)
	cfs_attachargs *argp;
	CLIENT *clnt;
{
	static cfsstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADMPROC_ATTACH,
		(xdrproc_t) xdr_cfs_attachargs, (caddr_t) argp,
		(xdrproc_t) xdr_cfsstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

cfsstat *
admproc_detach_2(argp, clnt)
	cfs_detachargs *argp;
	CLIENT *clnt;
{
	static cfsstat clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, ADMPROC_DETACH,
		(xdrproc_t) xdr_cfs_detachargs, (caddr_t) argp,
		(xdrproc_t) xdr_cfsstat, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
