.TH CCAT 8 ""
.SH NAME
ccat
.SH SYNOPSIS
.B ccat
[ \-\fB3ms\fP ]
\fIfile\fP
[ ... ]
.SH DESCRIPTION
\fBccat\fP prompts for a passphrase and decrypts (onto standard
output) the specified CFS encrypted files.  If a corresponding CFS IV
file (.pvect_*) file exists in the same directory, it is used to
perturb the file accordingly.  By default, files are decrypted using
standard 2-key hybrid mode single-DES.  The \-\fB3\fP option specifies
2-key hybrid mode triple DES.  The \-\fBm\fP option specifies 1-key
hybrid mode MacGuffin, and \-\fBs\fP specifies SAFER-SK128.
.LP
\fBccat\fP is intended to assist in emergency access to CFS
directories when no machine running a CFS daemon is available.  It is
ordinarily used in conjunction with cname(8).
.SH SEE ALSO
cname(8)
.SH BUGS
Does not work with new format (1.3 and later) directories.
.LP
This program is just blindingly slow.  There's no way to tell if an
incorrect passphrase was entered, except that the program will produce
garbage output.
.SH AUTHOR
Matt Blaze; for information on cfs, email to cfs@research.att.com.

