.TH CDETACH 1 ""
.SH NAME
cdetach - detach encrypted directory from CFS
.SH SYNOPSIS
.B cdetach
\fIname\fP
.SH DESCRIPTION
\fBcdettach\fP removes the instance called \fIname\fP of an encrypted
directory (created with \fBcattach\fP(1)) from /crypt.  The underlying
encrypted version of the directory remains, of course, and may be
attached again when needed with \fBcattach\fP(1).
.SH EXAMPLE
.TP
cdetach mab
deletes /crypt/mab
.SH SEE ALSO
cfsd(8), cattach(1)
.SH BUGS
Anyone can cdetach anything, even directories attached by other users.
This can lead to irritating denial-of-service attacks.
.SH AUTHOR
Matt Blaze; for information on cfs, email to
cfs@research.att.com
