#!/bin/ksh

if [ -z "$1" ]; then
	echo Usage: cfssh directory
	exit
fi
export PS1="crypto:`basename $1`$ "
D=.$RANDOM.$RANDOM
cattach $1 $D || exit 1
echo "Directory is /crypt/$D"
cd /crypt/$D
D="             "
CWD=`/bin/pwd`
D=`basename $CWD`
PWD=$CWD
export RANDOM=0
exec /bin/sh -c "$SHELL ; cdetach $D"
