.TH CMKKEY 1 ""
.SH NAME
cmkkey - create secondary copy of CFS directory key
.SH SYNOPSIS
.B cmkkey
\fIolddir\fP \fInewdir\fP
.SH DESCRIPTION
\fBcmkkey\fP creates a secondary copy of the key for an encrypted
Cryptographic File System (CFS) directory.  The secondary key
is initially the same as the original key, but can be changed with the
.B cpasswd
command.
.LP
Only CFS 1.4 or later directories (and not created with cmkdir -o) can have
secondary key files.
.SH FILES
.TP
\fInewdir\fP/..k
New secondary encyrpted key file.
.TP
\fInewdir\fP/..data
Link to encrypted directory \fIolddir\fP.
.SH SEE ALSO
cfsd(8), cattach(1), cmkdir(1), cpasswd(1)
.SH BUGS
Any symbolic links in \fIolddir\fP are resolved at the time cmkkey
is run; this could cause \fInewdir\fP/..data to break if one of these
links moves.  (This can be fixed by re-linking to the correct place
by hand).
.SH AUTHOR
Matt Blaze; for information on cfs, email to cfs@research.att.com.
