.TH CPASSWD 1 ""
.SH NAME
cpasswd - change passphrase on cfs directory
.SH SYNOPSIS
.B cpasswd
\fIdirectory\fP
.SH DESCRIPTION
\fBcpasswd\fP changes the passphrase associated with a
Cryptographic File System (CFS) directory.  \fBcpasswd\fP prompts for
the old passphrase, and, if it is correct, a new passphrase, which
must be entered twice.  Passphrases must contain at least a minimum
number of characters (currently 16).
.LP
Only new format (CFS 1.3 or later) directories can have their
passphrases changed.
.SH FILES
.TP
\fIdirectory\fP/...
known-plaintext hash of the assigned keys.
.TP
\fIdirectory\fP/..c
identifies the cipher algorithm.
.TP
\fIdirectory\fP/..k
encrypted key file
.SH SEE ALSO
cfsd(8), cattach(1), cmkdir(1)
.SH BUGS
One passphrase per encrypted directory; there is no provision (yet)
for individual users' passphrases.
.SH AUTHOR
Matt Blaze; for information on cfs, email to cfs@research.att.com.
