esm_gen.c File Reference
#include <stdio.h>
#include `global.h`
#include `rsaref.h`
#include `esm.h`
Functions
main ()
printparams (dh) R_DH_PARAMS *dh
Function Documentation
main ()
Definition at line 27 of file esm_gen.c.
References dhparams, printparams(), randinit(), and rs.
28 {
29         R_DH_PARAMS dhparams[3];
30         unsigned char p0[512],p1[512],p2[512],g0[512],g1[512],g2[512];
31         int x;
32         
33         randinit();
34 
35         fprintf(stderr,"Generating 512\n");
36         dhparams[0].prime=p0;
37         dhparams[0].generator=g0;
38         if (x=R_GenerateDHParams(&dhparams[0],512,256,&rs))
39                 fprintf(stderr,"failed %x\n",x);
40         fprintf(stderr,"Generating 768\n");
41         dhparams[1].prime=p1;
42         dhparams[1].generator=g1;
43         if (x=R_GenerateDHParams(&dhparams[1],768,384,&rs))
44                 fprintf(stderr,"failed %x\n",x);
45         fprintf(stderr,"Generating 1024\n");
46         dhparams[2].prime=p2;
47         dhparams[2].generator=g2;
48         if (x=R_GenerateDHParams(&dhparams[2],1024,512,&rs))
49                 fprintf(stderr,"failed %x\n",x);
50         fprintf(stderr,"Printing\n");
51         printparams(dhparams);
52         exit(0);
53 }
printparams (dh)
Referenced by main().