esm_cipher.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <sys/time.h>
#include <signal.h>
#include `global.h`
#include `rsaref.h`
#include `esm.h`
Defines
#define BLANKLINE 0
#define TERM 1
#define NONE 2
#define SHORTKEY 3
#define MEDKEY 4
#define LONGKEY 5
#define HEX 6
#define FILENAME 7
Functions
cipherinit (master) int master
void procbit ()
randinit ()
int rnd8 ()
oldrandinit ()
getpubkey ()
createdh (param) int param
Variables
unsigned char check [8]
unsigned char skey1 [8]
unsigned char skey2 [8]
unsigned char skey3 [8]
unsigned char mkey1 [8]
unsigned char mkey2 [8]
unsigned char mkey3 [8]
unsigned char ivin [8]
unsigned char ivout [8]
R_RANDOM_STRUCT rs
R_DH_PARAMS dhparams [3]
unsigned char otherpub [MAXPUBKEY+2]
unsigned char ourpub [MAXPUBKEY+2]
unsigned char ourpriv [MAXPUBKEY]
int ourprivlen
int pklen
keystr inks
keystr outks
int secs
unsigned int bits
int verbose = 1
int size [3]
int keysize = 0
int master
Define Documentation
#define BLANKLINE 0
Definition at line 246 of file esm_cipher.c.
#define FILENAME 7
Definition at line 253 of file esm_cipher.c.
#define HEX 6
Definition at line 252 of file esm_cipher.c.
#define LONGKEY 5
Definition at line 251 of file esm_cipher.c.
#define MEDKEY 4
Definition at line 250 of file esm_cipher.c.
#define NONE 2
Definition at line 248 of file esm_cipher.c.
#define SHORTKEY 3
Definition at line 249 of file esm_cipher.c.
#define TERM 1
Definition at line 247 of file esm_cipher.c.
Function Documentation
cipherinit (master)
createdh (param)
Referenced by startsession().
getpubkey ()
Definition at line 259 of file esm_cipher.c.
260 {
261         fprintf(stderr,"Calculator not implemented, sorry\n");
262         return;
263 }
oldrandinit ()
Definition at line 210 of file esm_cipher.c.
References n, rnd8(), rs, and verbose.
211 {
212         unsigned int n;
213         unsigned char b[18];
214         struct timeval tv;
215         
216         R_RandomInit(&rs);
217         R_GetRandomBytesNeeded(&n,&rs); /* but we ignore */
218         /* RSAREF wants 256 bytes, which is an awful lot at 4bps.  we
219            really only need enough to do justice to the entropy of
220            the block cipher (3des), so we just generate 18. */
221            
222         if (verbose)
223                 fprintf(stderr,"Randomizing (takes about 45 secs)...");
224         fflush(stderr);
225         for (n=0; n<18; n++) {
226                 b[n]=rnd8();
227                 if (verbose && (n%4==3)) {
228                         fprintf(stderr,".");
229                         fflush(stderr);
230                 }
231         }
232         while (R_GetRandomBytesNeeded(&n,&rs), (n>0)) {
233                 R_RandomUpdate(&rs,b,18);
234                 if (verbose)
235                         fprintf(stderr,".");
236         }
237         /* Just for good measure, we throw in a couple other things */
238         n=getpid();
239         R_RandomUpdate(&rs,(unsigned char*)&n,sizeof(n));
240         gettimeofday(&tv,NULL);
241         R_RandomUpdate(&rs,(unsigned char*)&tv,sizeof(tv));
242         if (verbose)
243                 fprintf(stderr,"done\n");
244 }
void procbit ()
Definition at line 133 of file esm_cipher.c.
References bits, procbit(), and secs.
Referenced by procbit(), and rnd8().
134 {
135         secs--;
136         bits |= ((count ^ (count>>4)) & 0xf)<<(secs*4);
137         if (secs) {
138                 alarm(1);
139                 signal(SIGALRM,procbit);
140                 getuid();       /* do a syscall to slow things a bit */
141         }
142 }
randinit ()
Definition at line 155 of file esm_cipher.c.
References n, rs, and verbose.
Referenced by main().
156 {
157         unsigned int n;
158         int i;
159         struct timeval tv;
160         unsigned long truerand();
161         unsigned char b[20];
162         
163         R_RandomInit(&rs);
164         if (verbose) {
165                 fprintf(stderr,"randomizing...");
166                 fflush(stderr);
167         }
168         /* we just grab 160 truerand bits and keep feeding them
169            over and over to R_RandomUpdate until it's happy */
170         for (i=0; i<20; i++) {
171                 b[i]=randbyte();
172                 fprintf(stderr,".");
173         }
174         while (R_GetRandomBytesNeeded(&n,&rs), (n>0)) {
175                 R_RandomUpdate(&rs,b,sizeof(b));
176         }
177         if (verbose) {
178                 fprintf(stderr,"done\n");
179                 fflush(stderr);
180         }
181 }
int rnd8 ()
Definition at line 191 of file esm_cipher.c.
References bits, procbit(), and secs.
Referenced by oldrandinit().
192 {
193         secs=2;
194         bits=0;
195         signal(SIGALRM,procbit);
196         alarm(1);
197         getpid();
198         while (secs)
199                 count++;
200         return bits;
201         
202 }
Variable Documentation
unsigned int bits
Definition at line 132 of file esm_cipher.c.
Referenced by procbit(), and rnd8().
unsigned char check[8]
Definition at line 30 of file esm_cipher.c.
R_DH_PARAMS dhparams[3]
Definition at line 43 of file esm_cipher.c.
keystr inks
Definition at line 51 of file esm_cipher.c.
unsigned char ivin[8]
Definition at line 38 of file esm_cipher.c.
unsigned char ivout[8]
Definition at line 39 of file esm_cipher.c.
int keysize = 0
Definition at line 257 of file esm_cipher.c.
int master
Definition at line 282 of file esm_cipher.c.
unsigned char mkey1[8]
Definition at line 35 of file esm_cipher.c.
unsigned char mkey2[8]
Definition at line 36 of file esm_cipher.c.
unsigned char mkey3[8]
Definition at line 37 of file esm_cipher.c.
unsigned char otherpub[MAXPUBKEY+2]
Definition at line 45 of file esm_cipher.c.
unsigned char ourpriv[MAXPUBKEY]
Definition at line 47 of file esm_cipher.c.
int ourprivlen
Definition at line 48 of file esm_cipher.c.
unsigned char ourpub[MAXPUBKEY+2]
Definition at line 46 of file esm_cipher.c.
Referenced by sltranspub(), and startsession().
keystr outks
Definition at line 51 of file esm_cipher.c.
int pklen
Definition at line 49 of file esm_cipher.c.
Referenced by startsession().
R_RANDOM_STRUCT rs
Definition at line 41 of file esm_cipher.c.
Referenced by main(), oldrandinit(), and randinit().
int secs
Definition at line 131 of file esm_cipher.c.
Referenced by procbit(), and rnd8().
int size[3]
Definition at line 255 of file esm_cipher.c.
unsigned char skey1[8]
Definition at line 32 of file esm_cipher.c.
unsigned char skey2[8]
Definition at line 33 of file esm_cipher.c.
unsigned char skey3[8]
Definition at line 34 of file esm_cipher.c.
int verbose = 1
Definition at line 144 of file esm_cipher.c.
Referenced by oldrandinit(), and randinit().