







<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="generator" content="0.11 (1dfb99f11c67)" />
<meta http-equiv="X-UA-Compatible" content="IE=8" />
<link rel="icon" href="/source/default/img/icon.png" type="image/png" />
<link rel="stylesheet" type="text/css" media="all"
    title="Default" href="/source/default/style.css" />
<link rel="stylesheet" type="text/css" href="/source/default/print.css" media="print" />
<link rel="stylesheet" type="text/css" href="/source/default/jquery.tooltip.css" />

<link rel="search" href="/source/opensearch"
    type="application/opensearchdescription+xml"
    title="MetaGer Code Search" />
<script type="text/javascript" src="/source/jquery-1.4.4.min.js"></script>
<script type="text/javascript" src="/source/jquery.tooltip-1.3.pack.js"></script>

<script type="text/javascript" src="/source/utils.js"></script>
<title>Cross Reference: /DragonFly-BSD/usr.bin/uniq/Makefile</title>
</head><body>
<script type="text/javascript">/* <![CDATA[ */
    document.hash = 'null';document.rev = '';document.link = '/source/xref/DragonFly-BSD/usr.bin/uniq/Makefile';document.annotate = false;
    document.domReady.push(function() {domReadyMast();});
    document.pageReady.push(function() { pageReadyMast();});
/* ]]> */</script>
<div id="page">
    <div id="whole_header">
        <form action="/source/search">
<div id="header">
<a href="/source/"><span id="MastheadLogo"></span></a>



    <div id="pagetitle"><span id="filename"
                    >Cross Reference: Makefile</span></div>
</div>
<div id="Masthead">
    <tt><a href="/source/xref/">xref</a>: /<a href="/source/xref/DragonFly-BSD/">DragonFly-BSD</a>/<a href="/source/xref/DragonFly-BSD/usr.bin/">usr.bin</a>/<a href="/source/xref/DragonFly-BSD/usr.bin/uniq/">uniq</a>/<a href="/source/xref/DragonFly-BSD/usr.bin/uniq/Makefile">Makefile</a></tt>
</div>
<div id="bar">
    <ul>
        <li><a href="/source/"><span id="home"></span>Home</a></li><li><a href="/source/history/DragonFly-BSD/usr.bin/uniq/Makefile"><span id="history"></span>History</a></li><li><a href="#" onclick="javascript:get_annotations(); return false;"
            ><span class="annotate"></span>Annotate</a></li><li><a href="#" onclick="javascript:lntoggle();return false;"
            title="Show or hide line numbers (might be slower if file has more than 10 000 lines)."><span id="line"></span>Line#</a></li><li><a
            href="#" onclick="javascript:lsttoggle();return false;"
            title="Show or hide symbol list."><span id="defbox"></span>Navigate</a></li><li><a href="/source/raw/DragonFly-BSD/usr.bin/uniq/Makefile"><span id="download"></span>Download</a></li><li><input type="text" id="search" name="q" class="q" />
            <input type="submit" value="Search" class="submit" /></li><li><input type="checkbox" name="path" value="/DragonFly-BSD/usr.bin/uniq/" /> only in <b>Makefile</b></li>
        
    </ul>
    <input type="hidden" name="project" value="DragonFly-BSD" />
</div>
        </form>
    </div>
<div id="content">

<script type="text/javascript">/* <![CDATA[ */
document.pageReady.push(function() { pageReadyList();});
/* ]]> */</script>

<div id="src">
    <pre><script type="text/javascript">/* <![CDATA[ */
function get_sym_list(){return [["Macro","xm",[["PROG",4]]]];} /* ]]> */</script><a class="l" name="1" href="#1">1</a><span class="c">#	@(#)Makefile	8.1 (Berkeley) 6/6/93</span>
<a class="l" name="2" href="#2">2</a><span class="c"># $DragonFly: <a href="/source/s?path=src/">src</a>/<a href="/source/s?path=src/usr.bin/">usr.bin</a>/<a href="/source/s?path=src/usr.bin/uniq/">uniq</a>/<a href="/source/s?path=src/usr.bin/uniq/Makefile">Makefile</a>,v 1.3 2007/08/27 16:51:00 pavalos Exp $</span>
<a class="l" name="3" href="#3">3</a>
<a class="l" name="4" href="#4">4</a><a class="xm" name="PROG"/><a href="/source/s?refs=PROG&amp;project=DragonFly-BSD" class="xm">PROG</a>=	<a href="/source/s?defs=uniq&amp;project=DragonFly-BSD">uniq</a>
<a class="l" name="5" href="#5">5</a>
<a class="l" name="6" href="#6">6</a>.<a href="/source/s?defs=include&amp;project=DragonFly-BSD">include</a> &lt;<a href="/source/s?path=bsd.prog.mk&amp;project=DragonFly-BSD">bsd.prog.mk</a>&gt;
<a class="l" name="7" href="#7">7</a></pre>
</div>
    <div id="footer">
<p><a href="http://www.opensolaris.org/os/project/opengrok/"
 title="Served by OpenGrok"><span id="fti"></span></a></p>
<p>Index created: Mon Nov 12 14:38:08 CET 2012.</p>
<p>The index contains 4007 repositories, grouped in 366 projects.</p>
<p>MetaGer Code Search - <a href="http://www.metager.de/impressum.html">Contact</a></p>
    
    </div>
    </div>
</div>
</body>
</html>


